const $=id=>document.getElementById(id), KEY='ideal-gas-preview:v1';
const gasNames=['Air','Nitrogen','Oxygen','Carbon dioxide','Carbon monoxide'];
let current, identity, mode='practice', attempt=0, fields=[];
function hash(s){let h=2166136261;for(const c of s){h=Math.imul(h^c.charCodeAt(0),16777619)}return h>>>0}
function close(a,b,abs=.05,rel=.01){return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=Math.max(abs,rel*Math.abs(b))}
function val(id){const raw=$(id)?.value;return raw===undefined||raw.trim()===''?NaN:Number(raw)}
function field(id,label,unit){fields.push(id);return `<div class="property-field"><label for="${id}">${label}</label><div class="input-row"><input id="${id}" type="number" step="any" inputmode="decimal"><span class="unit">${unit}</span></div><div id="f-${id}" class="feedback" aria-live="polite"></div></div>`}
function step(n,title,body){return `<section class="step"><div class="step-heading"><span>0${n}</span><h2>${title}</h2></div>${body}</section>`}
function interp(id,title){return `<details class="interp"><summary>${title} — optional interpolation worksheet</summary><p>y = ylow + (T − Tlow)/(Thigh − Tlow) × (yhigh − ylow). Use adjacent rows from the correct gas table. No extrapolation.</p><div class="grid">${field(id+'T','Target temperature','K')}${field(id+'L','Lower temperature','K')}${field(id+'H','Upper temperature','K')}${field(id+'Yl','Lower property','table units')}${field(id+'Yh','Upper property','table units')}${field(id+'Y','Interpolated result','table units')}</div></details>`}
function generate(seed){return {id:seed,gas:gasNames[seed%5],T1:320+(seed%7)*15,T2:(seed%2?270:590)+(seed%5)*15,P1:100+(seed%4)*25,P2:125+(seed%3)*25,V1:Math.round((.6+(seed%4)*.2)*100)/100,unknown:['P2','V2','T2','m'][seed%4]}}
function render(){fields=[];$('welcome').hidden=true;$('workspace').hidden=false;$('badge').textContent=mode==='practice'?'Practice preview':'Official preview — not connected';$('next').hidden=mode==='official';$('caseTitle').textContent=current.gas+' · '+(current.T2>current.T1?'heating':'cooling');let g=`<p>Case ${current.id}</p><p>State 1: P₁ = ${current.P1} kPa, V₁ = ${current.V1} m³, T₁ = ${current.T1} K</p>`;g+=`<p>State 2: ${current.unknown==='P2'?'P₂ = ?':`P₂ = ${current.P2} kPa`}, ${current.unknown==='T2'?'T₂ = ?':`T₂ = ${current.T2} K`}</p><p id="derivedGiven"></p><p>Find ${current.unknown}, v₁, v₂, Δu, Δh, ΔU, and ΔH using both methods.</p><p>Look up M and R̄ from A–1 first. The preview derives the remaining given once those values are entered.</p>`;$('givens').innerHTML=g;
$('steps').innerHTML=step(1,'State properties',`<p>Use Table A–1 for ${current.gas}. Until verified data are loaded, M and R̄ cannot be independently graded.</p><div class="grid">${field('M','Molar mass M','kg/kmol')}${field('Rb','Universal gas constant R̄','kJ/(kmol·K)')}${field('R','Gas constant R','kJ/(kg·K)')}${field('m','Fixed mass m','kg')}${field('P2','Pressure P₂','kPa')}${field('V2','Total volume V₂','m³')}${field('T2','Temperature T₂','K')}${field('v1','Specific volume v₁','m³/kg')}${field('v2','Specific volume v₂','m³/kg')}</div>`)+step(2,'Constant-specific-heat method',`<p>Use A–20 for ${current.gas} at Tavg, with interpolation as needed. Hold cp and cv constant over this interval.</p><div class="grid">${field('avg','Average temperature','K')}${field('cp','cp at Tavg','kJ/(kg·K)')}${field('cv','cv at Tavg','kJ/(kg·K)')}${field('duc','Δu constant','kJ/kg')}${field('dhc','Δh constant','kJ/kg')}${field('DUc','ΔU constant','kJ')}${field('DHc','ΔH constant','kJ')}</div>${interp('icp','cp at Tavg')}${interp('icv','cv at Tavg')}`)+step(3,'Variable-specific-heat method',`<p>Use ${current.gas==='Air'?'A–22, specific properties in kJ/kg':'A–23, molar properties in kJ/kmol; divide the differences by M'}. Enter the matching gas and table.</p><label for="table">Table used</label><select id="table"><option value="">Choose</option><option>A–20</option><option>A–22</option><option>A–23</option></select><label for="lookupGas">Gas used</label><select id="lookupGas"><option value="">Choose</option>${gasNames.map(x=>`<option>${x}</option>`).join('')}</select><p id="tableFeedback" aria-live="polite"></p><div class="grid">${['u1','u2','h1','h2'].map(x=>field(x,(current.gas==='Air'?'':'Molar ')+x,current.gas==='Air'?'kJ/kg':'kJ/kmol')).join('')}${field('duv','Δu variable','kJ/kg')}${field('dhv','Δh variable','kJ/kg')}${field('DUv','ΔU variable','kJ')}${field('DHv','ΔH variable','kJ')}</div>${['u1','u2','h1','h2'].map(x=>interp('i'+x,x+' lookup')).join('')}`)+step(4,'Comparison',`<p>Compare magnitude and sign. Neither method is guaranteed always to give a higher result. Signed difference = constant − variable. Relative difference = 100 × |constant − variable| / |variable|; undefined when variable is zero and constant is nonzero.</p><div class="grid">${field('diffu','Signed Δu method difference','kJ/kg')}${field('diffh','Signed Δh method difference','kJ/kg')}</div><label for="reflection">Explain the comparison</label><textarea id="reflection"></textarea><p id="comparison"></p>`)+step(5,'Submit',`<p>Official saving is disabled until verified source data and a separate backend are configured. Work is restored locally on this browser. Table-dependent answers cannot yet receive an official grade.</p>`);
for(const id of ['table','lookupGas','reflection'])fields.push(id);for(const id of fields)$(id).addEventListener('input',()=>{if(id==='M'||id==='Rb')derive();save()});derive();}
function expected(){let R=val('Rb')/val('M');if(!(R>0&&val('M')>0&&val('Rb')>0))return null;let m=current.P1*current.V1/(R*current.T1),V2=m*R*current.T2/current.P2;return {R,m,P2:current.P2,V2,T2:current.T2,v1:current.V1/m,v2:V2/m,avg:(current.T1+current.T2)/2}}
function derive(){let e=expected();$('derivedGiven').textContent=e?(current.unknown==='m'?`State 2: V₂ = ${e.V2.toPrecision(9)} m³`:`Fixed mass m = ${e.m.toPrecision(9)} kg`)+(current.unknown==='P2'||current.unknown==='T2'?`; V₂ = ${e.V2.toPrecision(9)} m³`:''):'Enter positive M and R̄ to derive the remaining given.'}
function save(){try{localStorage.setItem(KEY,JSON.stringify({identity,mode,attempt,current,answers:Object.fromEntries(fields.map(id=>[id,$(id).value]))}))}catch{$('results').textContent='Browser storage unavailable. Keep this tab open to preserve work.'}}
function check(){let e=expected(),fail=0;function test(id,target,hint='',abs=.05){let ok=close(val(id),target,abs);$('f-'+id).textContent=ok?'✓ Arithmetic consistent':'Check: '+(hint||'enter a value and review the equation.');$('f-'+id).className='feedback '+(ok?'correct':'incorrect');$(id).setAttribute('aria-invalid',String(!ok));if(!ok)fail++}
if(!e){$('results').textContent='Enter positive molar mass and R̄ from Table A–1 first.';return}for(const [id,n]of Object.entries(e))test(id,n,id.includes('T')||id==='avg'?'Use Kelvin, not Celsius.':'Use kPa, m³, kg, and R in kJ/(kg·K); V is total volume.',id==='R'||id.startsWith('v')||id==='V2'||id==='m'?.001:.05);
let dt=e.T2-current.T1;for(const [id,n]of Object.entries({duc:val('cv')*dt,dhc:val('cp')*dt,DUc:e.m*val('cv')*dt,DHc:e.m*val('cp')*dt}))test(id,n,id.startsWith('D')?'Multiply the specific energy change by mass; units are kJ.':'Use T₂ − T₁, including the cooling sign. Select cp and cv at Tavg, not automatically 300 K.');
let scale=current.gas==='Air'?1:val('M'),du=(val('u2')-val('u1'))/scale,dh=(val('h2')-val('h1'))/scale;for(const [id,n]of Object.entries({duv:du,dhv:dh,DUv:e.m*du,DHv:e.m*dh}))test(id,n,id.startsWith('D')?'Multiply by mass for total kJ.':'Subtract state 1 from state 2; convert kJ/kmol to kJ/kg by dividing by M for gases other than air.');test('diffu',val('duc')-val('duv'));test('diffh',val('dhc')-val('dhv'));
let tableOK=$('table').value===(current.gas==='Air'?'A–22':'A–23')&&$('lookupGas').value===current.gas;$('tableFeedback').textContent=tableOK?'✓ Correct table and gas selected.':'Select the correct gas and A–22 for air or A–23 for other gases.';if(!tableOK)fail++;
for(const id of ['icp','icv','iu1','iu2','ih1','ih2']){if(!['T','L','H','Yl','Yh','Y'].some(s=>$(id+s).value!==''))continue;let t=val(id+'T'),lo=val(id+'L'),hi=val(id+'H'),target=id.startsWith('ic')?e.avg:id.endsWith('1')?current.T1:e.T2;if(!(hi>lo&&t>=lo&&t<=hi&&close(t,target,.05,.001))){$('f-'+id+'Y').textContent='Check bounds and target. No extrapolation; target must match Tavg or the state temperature.';fail++;continue}let result=val(id+'Yl')+(t-lo)/(hi-lo)*(val(id+'Yh')-val(id+'Yl'));test(id+'Y',result,'Use linear interpolation with the entered bounding rows.');let prop=id==='icp'?'cp':id==='icv'?'cv':id.slice(1);test(prop,result,'Transfer your interpolated result into the property field.',prop==='cp'||prop==='cv'?.002:.05)}
function pct(a,b){return b===0?(a===0?'0% (both zero)':'undefined (zero reference)'):(100*Math.abs(a-b)/Math.abs(b)).toFixed(2)+'%'}$('comparison').textContent='Relative differences from entered values: Δu '+pct(val('duc'),val('duv'))+', Δh '+pct(val('dhc'),val('dhv'))+'.';$('results').textContent=fail?`${fail} arithmetic or selection checks need review. Table values remain unverified.`:'Arithmetic checks pass. Table values are unverified; this is not an official grade or submission.';save();}
$('registration').onsubmit=event=>{event.preventDefault();identity={first:$('first').value.trim(),last:$('last').value.trim(),email:$('email').value.trim().toLowerCase(),section:$('section').value==='Other section'?$('other').value.trim():$('section').value};if(!identity.first||!identity.last||!identity.section||! /^[^\s@]+@my\.erau\.edu$/.test(identity.email))return;mode=$('mode').value;attempt=0;current=generate(hash(identity.email+'|ideal-gas-v1'));render();save()};$('section').onchange=()=>{$('otherWrap').hidden=$('section').value!=='Other section';$('other').required=!$('otherWrap').hidden};$('home').onclick=()=>{$('welcome').hidden=false;$('workspace').hidden=true};$('check').onclick=check;$('next').onclick=()=>{attempt++;current=generate(hash(identity.email+'|practice|'+attempt));render();save()};
try{let saved=JSON.parse(localStorage.getItem(KEY));if(saved?.identity&&saved?.current){identity=saved.identity;mode=saved.mode;attempt=saved.attempt;current=saved.current;$('first').value=identity.first;$('last').value=identity.last;$('email').value=identity.email;$('mode').value=mode;render();for(const [id,value]of Object.entries(saved.answers||{}))if($(id))$(id).value=value;derive()}}catch{};
